#!/usr/bin/env bash
#sets up load balancers
sudo apt install -y haproxy=1.5\*
file=/etc/haproxy/haproxy.cfg
sudo echo -e "frontend haproxynode
\tbind *:80
\tmode http
\tdefault_backend nodes" | sudo tee -a $file
sudo echo -e "backend nodes
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver 73379-web-01 52.72.8.186:80 check
\tserver 73379-web-02 3.85.141.116:80 check" | sudo tee -a $file
sudo service haproxy restart
